[bundle]
identifier = "moe.sftblw.remove-cargo-built-target"
publisher = "sftblw"
icon = ["assets/icon.png"]

[application]

default_platform = "desktop"
name = "Remove Cargo Built Target"
title = "Remove Cargo Built Target"
